USE BIBLIOTECA;

-- PROCEDURE DE BUSCAR AUTOR --

DROP PROCEDURE IF EXISTS buscarAutor;

DELIMITER $$
CREATE PROCEDURE buscarAutor (IN IDIN INT(11))

BEGIN
  SELECT * FROM AUTOR WHERE ID = IDIN;
END $$

DELIMITER ;

-- ------------------------------- --

-- PROCEDURE DE BUSCAR AUTORES --

DROP PROCEDURE IF EXISTS buscarAutores;

DELIMITER $$
CREATE PROCEDURE buscarAutores ()

BEGIN
  SELECT * FROM AUTOR;
END $$

DELIMITER ;

-- ------------------------------- --

-- PROCEDURE DE BUSCAR AUTORES DE UM LIVRO --

DROP PROCEDURE IF EXISTS buscarAutoresPorLivro;

DELIMITER $$
CREATE PROCEDURE buscarAutoresPorLivro (IN LIVROIN SMALLINT UNSIGNED)

BEGIN
  SELECT * FROM LIVRO_AUTOR WHERE LIVRO = LIVROIN;
END $$

DELIMITER ;

-- ------------------------------- --

-- PROCEDURE DE ADICIONAR AUTOR --

DROP PROCEDURE IF EXISTS adicionarAutor;

DELIMITER $$
CREATE PROCEDURE adicionarAutor (IN NOMEIN VARCHAR(100))

BEGIN
  INSERT INTO AUTOR (NOME) VALUES (NOMEIN);
END $$

DELIMITER ;

-- ------------------------------- --

-- PROCEDURE DE ADICIONAR AUTOR A UM LIVRO --

DROP PROCEDURE IF EXISTS adicionarAutorEmLivro;

DELIMITER $$
CREATE PROCEDURE adicionarAutorEmLivro (IN AUTORIN SMALLINT UNSIGNED, IN LIVROIN SMALLINT UNSIGNED)

BEGIN
  INSERT INTO LIVRO_AUTOR (AUTOR, LIVRO) VALUES (AUTORIN, LIVROIN);
END $$

DELIMITER ;

-- ------------------------------- --

-- PROCEDURE DE ATUALIZAR AUTOR --

DROP PROCEDURE IF EXISTS atualizarAutor;

DELIMITER $$
CREATE PROCEDURE atualizarAutor (IN IDIN SMALLINT UNSIGNED, IN NOMEIN VARCHAR(100))

BEGIN
  UPDATE AUTOR SET NOME = NOMEIN WHERE ID = IDIN;
END $$

DELIMITER ;

-- ------------------------------- --

-- PROCEDURE DE EXCLUIR AUTOR --

DROP PROCEDURE IF EXISTS excluirAutor;

DELIMITER $$
CREATE PROCEDURE excluirAutor (IN IDIN SMALLINT UNSIGNED)

BEGIN
  DELETE FROM AUTOR WHERE ID = IDIN;
END $$

DELIMITER ;

-- ------------------------------- --