-- CRIAÇÃO DO BANCO DE DADOS
CREATE DATABASE IF NOT EXISTS BIBLIOTECA;
USE BIBLIOTECA;

-- CRIAÇÃO DA TABELA DE LIVROS --
DROP TABLE IF EXISTS LIVRO;
CREATE TABLE LIVRO
(
  ID SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  TITULO VARCHAR(100) NOT NULL,
  EDITORA SMALLINT UNSIGNED,
  PUBLICACAO DATE NOT NULL
) ENGINE = InnoDB;

-- CRIAÇÃO DA TABELA DE AUTORES --
DROP TABLE IF EXISTS AUTOR;
CREATE TABLE AUTOR
(
  ID SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NOME VARCHAR(100) NOT NULL
) ENGINE = InnoDB;

-- CRIAÇÃO DA TABELA DE EDITORAS --
DROP TABLE IF EXISTS EDITORA;
CREATE TABLE EDITORA
(
  ID SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NOME VARCHAR(100) NOT NULL
) ENGINE = InnoDB;

-- CRIAÇÃO DA TABELA DE LIVRO-AUTOR --
DROP TABLE IF EXISTS LIVRO_AUTOR;
CREATE TABLE LIVRO_AUTOR
(
  LIVRO SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  AUTOR VARCHAR(100) NOT NULL,
  PRIMARY KEY (LIVRO, AUTOR)
) ENGINE = InnoDB;

-- CRIAÇÃO DA TABELA DE USUÁRIOS --
DROP TABLE IF EXISTS USUARIO;
CREATE TABLE USUARIO
(
  ID SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NOME VARCHAR(100) NOT NULL,
  LOGIN VARCHAR(100) NOT NULL UNIQUE,
  SENHA VARCHAR(255) NOT NULL,
  TIPO ENUM ('ADMIN', 'USUARIO') NOT NULL
) ENGINE = InnoDB;