USE BIBLIOTECA;

-- PROCEDURE DE BUSCAR EDITORA --

DROP PROCEDURE IF EXISTS buscarEditora;

DELIMITER $$
CREATE PROCEDURE buscarEditora(IN IDIN INT(11))

BEGIN
  SELECT * FROM EDITORA WHERE ID = IDIN;
END $$

DELIMITER ;

-- ------------------------------- --

-- PROCEDURE DE BUSCAR EDITORAS --

DROP PROCEDURE IF EXISTS buscarEditoras;

DELIMITER $$
CREATE PROCEDURE buscarEditoras()

BEGIN
  SELECT * FROM EDITORA;
END $$

DELIMITER ;

-- ------------------------------- --

-- PROCEDURE DE ADICIONAR EDITORA --

DROP PROCEDURE IF EXISTS adicionarEditora;

DELIMITER $$
CREATE PROCEDURE adicionarEditora(IN NOMEIN VARCHAR(100))

BEGIN
  INSERT INTO EDITORA (NOME) VALUES (NOMEIN);
END $$

DELIMITER ;

-- ------------------------------- --

-- PROCEDURE DE ATUALIZAR EDITORA --

DROP PROCEDURE IF EXISTS atualizarEditora;

DELIMITER $$
CREATE PROCEDURE atualizarEditora(IN IDIN SMALLINT UNSIGNED, IN NOMEIN VARCHAR(100))

BEGIN
  UPDATE EDITORA SET NOME = NOMEIN WHERE ID = IDIN;
END $$

DELIMITER ;

-- ------------------------------- --

-- PROCEDURE DE EXCLUIR EDITORA --

DROP PROCEDURE IF EXISTS excluirEditora;

DELIMITER $$
CREATE PROCEDURE excluirEditora(IN IDIN SMALLINT UNSIGNED)

BEGIN
  DELETE FROM EDITORA WHERE ID = IDIN;
END $$

DELIMITER ;

-- ------------------------------- --