USE BIBLIOTECA;

-- PROCEDURE DE BUSCAR LIVRO --

DROP PROCEDURE IF EXISTS buscarLivro;

DELIMITER $$
CREATE PROCEDURE buscarLivro (IN IDIN INT(11))

BEGIN
  SELECT * FROM LIVRO WHERE ID = IDIN;
END $$

DELIMITER ;

-- ------------------------------- --

-- PROCEDURE DE BUSCAR LIVROS --

DROP PROCEDURE IF EXISTS buscarLivros;

DELIMITER $$
CREATE PROCEDURE buscarLivros ()

BEGIN
  SELECT * FROM LIVRO;
END $$

DELIMITER ;

-- ------------------------------- --

-- PROCEDURE DE BUSCAR LIVROS DE UM AUTOR --

DROP PROCEDURE IF EXISTS buscarLivrosPorAutor;

DELIMITER $$
CREATE PROCEDURE buscarLivrosPorAutor (IN AUTORIN SMALLINT UNSIGNED)

BEGIN
  SELECT * FROM LIVRO_AUTOR WHERE AUTOR = AUTORIN;
END $$

DELIMITER ;

-- ------------------------------- --

-- PROCEDURE DE BUSCAR LIVROS DE UMA EDITORA --

DROP PROCEDURE IF EXISTS buscarLivrosPorEditora;

DELIMITER $$
CREATE PROCEDURE buscarLivrosPorEditora (IN EDITORAIN SMALLINT UNSIGNED)

BEGIN
  SELECT * FROM LIVRO WHERE EDITORA = EDITORAIN;
END $$

DELIMITER ;

-- ------------------------------- --

-- PROCEDURE DE ADICIONAR LIVRO --

DROP PROCEDURE IF EXISTS adicionarLivro;

DELIMITER $$
CREATE PROCEDURE adicionarLivro (IN TITULOIN VARCHAR(100), IN PUBLICACAOIN DATE)

BEGIN
  INSERT INTO LIVRO (TITULO, PUBLICACAO) VALUES (TITULOIN, PUBLICACAOIN);
END $$

DELIMITER ;

-- ------------------------------- --

-- PROCEDURE DE ADICIONAR LIVRO COM EDITORA --

DROP PROCEDURE IF EXISTS adicionarLivroComEditora;

DELIMITER $$
CREATE PROCEDURE adicionarLivroComEditora (IN TITULOIN VARCHAR(100), IN EDITORAIN SMALLINT UNSIGNED, IN PUBLICACAOIN DATE)

BEGIN
  INSERT INTO LIVRO (TITULO, EDITORA, PUBLICACAO) VALUES (TITULOIN, EDITORAIN, PUBLICACAOIN);
END $$

DELIMITER ;

-- ------------------------------- --

-- PROCEDURE DE ATUALIZAR LIVRO --

DROP PROCEDURE IF EXISTS atualizarLivro;

DELIMITER $$
CREATE PROCEDURE atualizarLivro (IN IDIN SMALLINT UNSIGNED, IN TITULOIN VARCHAR(100), IN PUBLICACAOIN DATE)

BEGIN
  UPDATE LIVRO SET TITULO = TITULOIN, PUBLICACAO = PUBLICACAOIN WHERE ID = IDIN;
END $$

DELIMITER ;

call buscarLivros();

call atualizarLivro(4, 'ghfggf', '1990-01-01');

call logar('maurici', '7c4a8d09ca3762af61e59520943dc26494f8941b');

-- ------------------------------- --

-- PROCEDURE DE EXCLUIR LIVRO --

DROP PROCEDURE IF EXISTS excluirLivro;

DELIMITER $$
CREATE PROCEDURE excluirLivro (IN IDIN SMALLINT UNSIGNED)

BEGIN
  DELETE FROM LIVRO WHERE ID = IDIN;
END $$

DELIMITER ;

-- ------------------------------- --