USE BIBLIOTECA;

-- PROCEDURE DE BUSCAR USUARIO --

DROP PROCEDURE IF EXISTS buscarUsuario;

DELIMITER $$
CREATE PROCEDURE buscarUsuario(IN IDIN INT(11))

BEGIN
  SELECT * FROM USUARIO WHERE ID = IDIN;
END $$

DELIMITER ;

-- ------------------------------- --

-- PROCEDURE DE BUSCAR USUARIOS --

DROP PROCEDURE IF EXISTS buscarUsuarios;

DELIMITER $$
CREATE PROCEDURE buscarUsuarios()

BEGIN
  SELECT * FROM USUARIO;
END $$

DELIMITER ;

-- ------------------------------- --

-- PROCEDURE DE BUSCAR POR LOGIN E SENHA --

DROP PROCEDURE IF EXISTS logar;

DELIMITER $$
CREATE PROCEDURE logar(IN LOGININ VARCHAR(100), IN SENHAIN VARCHAR(255))

BEGIN
  SELECT ID, NOME, LOGIN, TIPO FROM USUARIO WHERE LOGIN = LOGININ AND SENHA = SENHAIN;
END $$

DELIMITER ;

-- ------------------------------- --

-- PROCEDURE DE ADICIONAR USUARIO --

DROP PROCEDURE IF EXISTS adicionarUsuario;

DELIMITER $$
CREATE PROCEDURE adicionarUsuario(IN NOMEIN VARCHAR(100), IN LOGININ VARCHAR(100), IN SENHAIN VARCHAR(100), IN TIPOIN ENUM ('ADMIN', 'USUARIO'))

BEGIN
  INSERT INTO USUARIO (NOME, LOGIN, SENHA, TIPO) VALUES (NOMEIN, LOGININ, SENHAIN, TIPOIN);
END $$

DELIMITER ;

-- ------------------------------- --

-- PROCEDURE DE ATUALIZAR USUARIO --

DROP PROCEDURE IF EXISTS atualizarUsuario;

DELIMITER $$
CREATE PROCEDURE atualizarUsuario(IN IDIN SMALLINT UNSIGNED, IN NOMEIN VARCHAR(100), IN LOGININ VARCHAR(100), IN TIPOIN ENUM ('ADMIN', 'USUARIO'))

BEGIN
  UPDATE USUARIO
    SET NOME  = NOMEIN,
        LOGIN = LOGININ,
        TIPO  = TIPOIN
  WHERE ID = IDIN;
END $$

DELIMITER ;

-- ------------------------------- --

-- PROCEDURE DE EXCLUIR USUARIO --

DROP PROCEDURE IF EXISTS excluirUsuario;

DELIMITER $$
CREATE PROCEDURE excluirUsuario(IN IDIN SMALLINT UNSIGNED)

BEGIN
  DELETE FROM USUARIO WHERE ID = IDIN;
END $$

DELIMITER ;

-- ------------------------------- --